/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "app-config": {
        "notFound": string;
        "alreadyExists": string;
        "unauthorized": string;
        "nameAlreadyExists": string;
        "nameNeedsToBeUnique": string;
    };
    "auth": {
        "emailAlreadyExists": string;
        "emailNotFound": string;
        "invalidEmailOrPassword": string;
        "invalidOldPassword": string;
        "invalidResetToken": string;
        "invalidSession": string;
        "loginFailed": string;
        "loginViaProvider": string;
        "passwordInvalid": string;
        "passwordRequired": string;
        "registrationFailed": string;
        "userNotFound": string;
    };
    "emailForgotPassword": {
        "subject": string;
        "text": string;
        "html": string;
        "action": string;
    };
    "emailSupportRequest": {
        "html": string;
        "subject": string;
        "text": string;
    };
    "errors": {
        "unauthorized": string;
        "notFound": string;
        "conflict": string;
        "internalServerError": string;
        "badRequest": string;
        "unprocessableEntity": string;
    };
    "locations": {
        "locationMissingTimezone": string;
        "pickupInPast": string;
        "pickupTooFarInFuture": string;
        "pickupOutsideBusinessHours": string;
    };
    "mail": {
        "footer": string;
        "defaultName": string;
    };
    "merchants": {
        "alreadyExists": string;
        "doesNotExist": string;
        "invalidSquareResponse": string;
        "needSquareAuthorization": string;
        "needsCatalog": string;
        "needsStripeId": string;
        "invalidStripeResponse": string;
    };
    "orders": {
        "merchantNotFound": string;
        "merchantNoSquareId": string;
        "locationNoSquareId": string;
        "noMainLocation": string;
        "customerNoSquareId": string;
        "locationNoId": string;
        "invalidResponseFromSquare": string;
        "merchantNoSquareAccessToken": string;
        "orderNoSquareId": string;
        "orderExists": string;
        "orderNotFound": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
