/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "common": {
        "emailFooter": string;
    };
    "forgotPasswordEmail": {
        "subject": string;
        "text": string;
        "html": string;
        "action": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
