/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "authentication": {
        "emailFound": string;
        "emailNotFound": string;
        "invalidPassword": string;
        "loginFailed": string;
        "loginViaProvider": string;
        "oldPasswordInvalid": string;
        "passwordOrEmailInvalid": string;
        "passwordRequired": string;
        "refreshTokenInvalid": string;
        "registrationFailed": string;
        "sessionInvalid": string;
        "sessionNotFound": string;
        "userNotFound": string;
    };
    "errors": {
        "100": string;
        "101": string;
        "102": string;
        "103": string;
        "200": string;
        "201": string;
        "202": string;
        "203": string;
        "204": string;
        "205": string;
        "206": string;
        "300": string;
        "301": string;
        "302": string;
        "303": string;
        "304": string;
        "307": string;
        "308": string;
        "400": string;
        "401": string;
        "402": string;
        "403": string;
        "404": string;
        "405": string;
        "406": string;
        "407": string;
        "408": string;
        "409": string;
        "410": string;
        "411": string;
        "412": string;
        "413": string;
        "414": string;
        "415": string;
        "416": string;
        "417": string;
        "418": string;
        "421": string;
        "422": string;
        "424": string;
        "428": string;
        "429": string;
        "500": string;
        "501": string;
        "502": string;
        "503": string;
        "504": string;
        "505": string;
    };
    "mail": {
        "defaultName": string;
        "footer": string;
        "postContact": {
            "html": string;
            "subject": string;
            "text": string;
        };
        "postCustomerMe": {
            "html": string;
            "subject": string;
            "text": string;
        };
        "postMerchantMe": {
            "html": string;
            "subject": string;
            "text": string;
        };
        "postPasswordForgot": {
            "action": string;
            "html": string;
            "subject": string;
            "text": string;
        };
        "postSupport": {
            "html": string;
            "subject": string;
            "text": string;
        };
        "postSquarePaymentOrderCurrent": {
            "html": string;
            "subject": string;
            "text": string;
        };
        "onEventSquareFulfillmentUpdateCanceled": {
            "html": string;
            "subject": string;
            "text": string;
        };
        "onEventSquareFulfillmentUpdateCompleted": {
            "html": string;
            "subject": string;
            "text": string;
        };
        "onEventSquareFulfillmentUpdateFailed": {
            "html": string;
            "subject": string;
            "text": string;
        };
        "onEventSquareFulfillmentUpdatePrepared": {
            "html": string;
            "subject": string;
            "text": string;
        };
        "onEventSquareFulfillmentUpdateProposed": {
            "html": string;
            "subject": string;
            "text": string;
        };
        "onEventSquareFulfillmentUpdateReserved": {
            "html": string;
            "subject": string;
            "text": string;
        };
    };
    "messages": {
        "postSquarePaymentOrderCurrent": string;
        "onEventSquareFulfillmentUpdateCanceled": string;
        "onEventSquareFulfillmentUpdateCompleted": string;
        "onEventSquareFulfillmentUpdateFailed": string;
        "onEventSquareFulfillmentUpdatePrepared": string;
        "onEventSquareFulfillmentUpdateProposed": string;
        "onEventSquareFulfillmentUpdateReserved": string;
    };
    "moaSquare": {
        "appConfigsExists": string;
        "appConfigsNameExists": string;
        "appConfigsNotFound": string;
        "catalogsNotFound": string;
        "customersExists": string;
        "customersNotFound": string;
        "customersSquareIdNotFound": string;
        "fileNotFound": string;
        "idNotFound": string;
        "itemsNotFound": string;
        "locationsBusinessHoursNotFound": string;
        "locationsMainNotFound": string;
        "locationsNotFound": string;
        "locationsPickupInPast": string;
        "locationsPickupOutsideBusinessHours": string;
        "locationsPickupTooFarInFuture": string;
        "locationsSquareIdNotFound": string;
        "locationsTimezoneNotFound": string;
        "merchantIdOrPathRequired": string;
        "merchantsExists": string;
        "merchantsNeedsCatalog": string;
        "merchantsNotFound": string;
        "merchantsSquareAccessTokenNotFound": string;
        "merchantsSquareIdNotFound": string;
        "merchantsStripeIdNotFound": string;
        "merchantsTierNotFound": string;
        "ordersExists": string;
        "ordersNotFound": string;
        "ordersSquareIdNotFound": string;
        "paginationIsNaN": string;
        "squareIdNotFound": string;
        "squareInvalidResponse": string;
        "stripeInvalidResponse": string;
        "userTypeInvalid": string;
        "usersNotFound": string;
    };
    "users": {
        "idNotFound": string;
        "emailNotFound": string;
        "invalidInput": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
