name: NestJS API CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run e2e tests
        run: docker compose --env-file env-example -f docker-compose.ci.yaml -p ci up --build --exit-code-from api
